const districtData = {
  "central-delhi": [
    {
      name: "Green Delhi Initiative",
      type: "NGO",
      description: "Promotes green spaces and pollution control.",
      website: "https://greendelhi.org",
      location: "https://maps.google.com/?q=Green+Delhi+Initiative",
    },
    {
      name: "Clean Air Project",
      type: "Government Scheme",
      description: "Provides subsidies for electric vehicles.",
      website: "https://cleanairproject.in",
      location: "https://maps.google.com/?q=Clean+Air+Project",
    },
    {
      name: "Delhi Eco Club",
      type: "NGO",
      description: "Encourages environmental awareness among students.",
      website: "https://delhiecoclub.org",
      location: "https://maps.google.com/?q=Delhi+Eco+Club",
    },
    {
      name: "Water Conservation Program",
      type: "Government Scheme",
      description: "Focuses on rainwater harvesting and water conservation.",
      website: "https://waterconservation.gov.in",
      location: "https://maps.google.com/?q=Water+Conservation+Program",
    },
    {
      name: "Green Home Initiative",
      type: "NGO",
      description: "Promotes sustainable housing and green living.",
      website: "https://greenhomeinitiative.org",
      location: "https://maps.google.com/?q=Green+Home+Initiative",
    },
    {
      name: "Waste Management Delhi",
      type: "Organization",
      description: "Leads efforts in reducing plastic waste and recycling.",
      website: "https://wastemanagementdelhi.org",
      location: "https://maps.google.com/?q=Waste+Management+Delhi",
    },
  ],
  "east-delhi": [
    {
      name: "Eco Warriors",
      type: "NGO",
      description: "Focuses on river pollution and cleanup drives.",
      website: "https://ecowarriors.in",
      location: "https://maps.google.com/?q=Eco+Warriors",
    },
    {
      name: "Delhi Tree Plantation",
      type: "Organization",
      description: "Leads tree plantation campaigns.",
      website: "https://delhitreeplantation.org",
      location: "https://maps.google.com/?q=Delhi+Tree+Plantation",
    },
    {
      name: "Yamuna River Cleanup",
      type: "NGO",
      description: "Dedicated to cleaning the Yamuna River.",
      website: "https://yamunarivercleanup.org",
      location: "https://maps.google.com/?q=Yamuna+River+Cleanup",
    },
    {
      name: "Solar Delhi",
      type: "Government Scheme",
      description: "Provides incentives for solar panel installation.",
      website: "https://solardelhi.gov.in",
      location: "https://maps.google.com/?q=Solar+Delhi",
    },
    {
      name: "Zero Waste Campaign",
      type: "NGO",
      description: "Promotes zero-waste lifestyle and composting.",
      website: "https://zerowastecampaign.in",
      location: "https://maps.google.com/?q=Zero+Waste+Campaign",
    },
    {
      name: "Delhi Wildlife Protection",
      type: "Organization",
      description: "Works on protecting urban wildlife.",
      website: "https://delhiwildlifeprotection.org",
      location: "https://maps.google.com/?q=Delhi+Wildlife+Protection",
    },
  ],
  "new-delhi": [
    {
      name: "Green Earth Society",
      type: "NGO",
      description: "Works on afforestation and climate change awareness.",
      website: "https://greenearthsociety.com",
      location: "https://maps.google.com/?q=Green+Earth+Society",
    },
    {
      name: "Renewable Delhi",
      type: "Government Scheme",
      description: "Provides solar panel subsidies for homes.",
      website: "https://renewabledelhi.gov.in",
      location: "https://maps.google.com/?q=Renewable+Delhi",
    },
    {
      name: "Air Quality Monitoring Program",
      type: "Government Scheme",
      description: "Monitors and reports air quality levels in Delhi.",
      website: "https://airqualitymonitoring.gov.in",
      location: "https://maps.google.com/?q=Air+Quality+Monitoring+Delhi",
    },
    {
      name: "Urban Gardening Initiative",
      type: "NGO",
      description: "Encourages urban residents to grow their own food.",
      website: "https://urbangardeningdelhi.org",
      location: "https://maps.google.com/?q=Urban+Gardening+Delhi",
    },
    {
      name: "Eco Schools Program",
      type: "Organization",
      description: "Works with schools to make them more sustainable.",
      website: "https://ecoschoolsdelhi.org",
      location: "https://maps.google.com/?q=Eco+Schools+Delhi",
    },
    {
      name: "Delhi Renewable Energy Network",
      type: "NGO",
      description: "Promotes renewable energy adoption in Delhi.",
      website: "https://delhirenewable.org",
      location: "https://maps.google.com/?q=Delhi+Renewable+Energy+Network",
    },
  ],
  "north-delhi": [
    {
      name: "Green Canopy Initiative",
      type: "NGO",
      description: "Focuses on increasing green cover in North Delhi.",
      website: "https://greencanopy.org",
      location: "https://maps.google.com/?q=Green+Canopy+Initiative",
    },
    {
      name: "Clean Yamuna Project",
      type: "Government Scheme",
      description: "Aims to reduce industrial waste in the Yamuna River.",
      website: "https://cleanyamunaproject.gov.in",
      location: "https://maps.google.com/?q=Clean+Yamuna+Project",
    },
    {
      name: "Delhi Zero Waste Movement",
      type: "NGO",
      description: "Promotes waste segregation and recycling programs.",
      website: "https://delhizerowaste.org",
      location: "https://maps.google.com/?q=Delhi+Zero+Waste+Movement",
    },
    {
      name: "Eco Friendly Homes Initiative",
      type: "Government Scheme",
      description: "Offers incentives for eco-friendly home designs.",
      website: "https://ecofriendlyhomes.gov.in",
      location: "https://maps.google.com/?q=Eco+Friendly+Homes+Initiative",
    },
    {
      name: "North Delhi Biodiversity Park",
      type: "Organization",
      description: "Manages biodiversity conservation areas in North Delhi.",
      website: "https://ndbiodiversitypark.org",
      location: "https://maps.google.com/?q=North+Delhi+Biodiversity+Park",
    },
    {
      name: "Solar Rooftop Program",
      type: "Government Scheme",
      description: "Subsidies for rooftop solar panels in residential areas.",
      website: "https://solarrooftopdelhi.gov.in",
      location: "https://maps.google.com/?q=Solar+Rooftop+Program+Delhi",
    },
  ],
  "north-east-delhi": [
    {
      name: "Green Future Delhi",
      type: "NGO",
      description: "Educates citizens about environmental conservation.",
      website: "https://greenfuturedelhi.org",
      location: "https://maps.google.com/?q=Green+Future+Delhi",
    },
    {
      name: "Plastic-Free Delhi Campaign",
      type: "Government Scheme",
      description: "Aims to eliminate plastic waste from North-East Delhi.",
      website: "https://plasticfreedelhi.gov.in",
      location: "https://maps.google.com/?q=Plastic-Free+Delhi+Campaign",
    },
    {
      name: "Yamuna Biodiversity Park",
      type: "Organization",
      description: "A protected area for native plant and animal species.",
      website: "https://yamunaparkdelhi.org",
      location: "https://maps.google.com/?q=Yamuna+Biodiversity+Park",
    },
    {
      name: "Delhi Urban Farming Network",
      type: "NGO",
      description: "Supports rooftop and community gardening in Delhi.",
      website: "https://delhiurbanfarming.in",
      location: "https://maps.google.com/?q=Delhi+Urban+Farming+Network",
    },
    {
      name: "Eco Transport Scheme",
      type: "Government Scheme",
      description: "Encourages use of bicycles and electric vehicles.",
      website: "https://ecotransportdelhi.gov.in",
      location: "https://maps.google.com/?q=Eco+Transport+Scheme+Delhi",
    },
    {
      name: "Save Delhi Lakes Initiative",
      type: "NGO",
      description: "Works towards restoring and maintaining Delhi's lakes.",
      website: "https://savedelhilakes.org",
      location: "https://maps.google.com/?q=Save+Delhi+Lakes+Initiative",
    },
  ],

  "north-west-delhi": [
    {
      name: "Green Belt Initiative",
      type: "NGO",
      description: "Focuses on expanding green zones and public parks.",
      website: "https://greenbeltinitiative.org",
      location: "https://maps.google.com/?q=Green+Belt+Initiative",
    },
    {
      name: "Delhi Waste Management Program",
      type: "Government Scheme",
      description: "Promotes waste segregation and composting.",
      website: "https://delhiwastemanagement.gov.in",
      location: "https://maps.google.com/?q=Delhi+Waste+Management+Program",
    },
    {
      name: "North West Air Quality Initiative",
      type: "NGO",
      description: "Monitors and works on improving air quality.",
      website: "https://nwaqi.org",
      location: "https://maps.google.com/?q=North+West+Air+Quality+Initiative",
    },
    {
      name: "Delhi Solar Initiative",
      type: "Government Scheme",
      description: "Provides subsidies for solar energy adoption.",
      website: "https://delhisolar.gov.in",
      location: "https://maps.google.com/?q=Delhi+Solar+Initiative",
    },
    {
      name: "Eco Transport North West",
      type: "Organization",
      description: "Advocates for non-motorized transport solutions.",
      website: "https://ecotransportnw.org",
      location: "https://maps.google.com/?q=Eco+Transport+North+West",
    },
    {
      name: "Ridge Forest Conservation",
      type: "NGO",
      description: "Works to protect the Ridge Forest and biodiversity.",
      website: "https://ridgeforestconservation.org",
      location: "https://maps.google.com/?q=Ridge+Forest+Conservation",
    },
  ],
  shahdara: [
    {
      name: "Yamuna River Cleanup",
      type: "NGO",
      description: "Leads efforts to clean and restore the Yamuna River.",
      website: "https://yamunacleanup.org",
      location: "https://maps.google.com/?q=Yamuna+River+Cleanup",
    },
    {
      name: "Delhi Eco Housing Scheme",
      type: "Government Scheme",
      description: "Encourages eco-friendly housing projects.",
      website: "https://delhiecohousing.gov.in",
      location: "https://maps.google.com/?q=Delhi+Eco+Housing+Scheme",
    },
    {
      name: "Plastic-Free Shahdara",
      type: "NGO",
      description: "Works towards reducing plastic waste in Shahdara.",
      website: "https://plasticfreeshahdara.org",
      location: "https://maps.google.com/?q=Plastic-Free+Shahdara",
    },
    {
      name: "Delhi Water Conservation Program",
      type: "Government Scheme",
      description: "Encourages rainwater harvesting in Shahdara.",
      website: "https://delhiwaterconservation.gov.in",
      location: "https://maps.google.com/?q=Delhi+Water+Conservation+Program",
    },
    {
      name: "Community Urban Gardens",
      type: "Organization",
      description: "Supports urban gardening and composting programs.",
      website: "https://communityurbangardens.org",
      location: "https://maps.google.com/?q=Community+Urban+Gardens",
    },
    {
      name: "Clean Shahdara Initiative",
      type: "NGO",
      description: "Runs sanitation and hygiene awareness programs.",
      website: "https://cleanshahdara.org",
      location: "https://maps.google.com/?q=Clean+Shahdara+Initiative",
    },
  ],
  "south-delhi": [
    {
      name: "South Delhi Green Initiative",
      type: "NGO",
      description: "Focuses on urban afforestation and clean energy advocacy.",
      website: "https://southdelhigreen.org",
      location: "https://maps.google.com/?q=South+Delhi+Green+Initiative",
    },
    {
      name: "Air Quality Improvement Program",
      type: "Government Scheme",
      description:
        "Monitors air quality and provides subsidies for air purifiers.",
      website: "https://airqualitydelhi.gov.in",
      location: "https://maps.google.com/?q=Air+Quality+Improvement+Program",
    },
    {
      name: "South Delhi Zero Waste Campaign",
      type: "NGO",
      description: "Runs awareness programs on waste reduction and composting.",
      website: "https://zerowastesouthdelhi.org",
      location: "https://maps.google.com/?q=South+Delhi+Zero+Waste+Campaign",
    },
    {
      name: "Solar Rooftop Scheme",
      type: "Government Scheme",
      description: "Provides financial incentives for installing solar panels.",
      website: "https://delhisolarrooftop.gov.in",
      location: "https://maps.google.com/?q=Solar+Rooftop+Scheme",
    },
    {
      name: "Aravalli Forest Conservation",
      type: "Organization",
      description: "Works on restoring the Aravalli forests in South Delhi.",
      website: "https://aravalliconservation.org",
      location: "https://maps.google.com/?q=Aravalli+Forest+Conservation",
    },
    {
      name: "Green Transport South Delhi",
      type: "NGO",
      description: "Promotes the use of bicycles and electric vehicles.",
      website: "https://greentransportsouthdelhi.org",
      location: "https://maps.google.com/?q=Green+Transport+South+Delhi",
    },
  ],
  "south-east-delhi": [
    {
      name: "South East Delhi Eco Club",
      type: "NGO",
      description:
        "Encourages schools and colleges to adopt sustainable practices.",
      website: "https://sedeco.org",
      location: "https://maps.google.com/?q=South+East+Delhi+Eco+Club",
    },
    {
      name: "Water Conservation Initiative",
      type: "Government Scheme",
      description: "Promotes rainwater harvesting and water recycling.",
      website: "https://waterconservationdelhi.gov.in",
      location: "https://maps.google.com/?q=Water+Conservation+Initiative",
    },
    {
      name: "South East Plastic-Free Drive",
      type: "NGO",
      description: "Runs campaigns to eliminate plastic usage in markets.",
      website: "https://plasticfreesoutheastdelhi.org",
      location: "https://maps.google.com/?q=South+East+Plastic-Free+Drive",
    },
    {
      name: "Urban Farming Initiative",
      type: "Organization",
      description: "Helps communities set up rooftop gardens and urban farms.",
      website: "https://urbanfarmingdelhi.org",
      location: "https://maps.google.com/?q=Urban+Farming+Initiative",
    },
    {
      name: "Delhi Biodiversity Restoration",
      type: "NGO",
      description: "Works on reviving lakes and wetlands in the area.",
      website: "https://delhibiodiversity.org",
      location: "https://maps.google.com/?q=Delhi+Biodiversity+Restoration",
    },
    {
      name: "Eco-Friendly Transport Initiative",
      type: "Government Scheme",
      description: "Subsidizes electric rickshaws and CNG buses.",
      website: "https://delhiecomobility.gov.in",
      location: "https://maps.google.com/?q=Eco-Friendly+Transport+Initiative",
    },
  ],

  "south-west-delhi": [
    {
      name: "South West Green Movement",
      type: "NGO",
      description: "Focuses on reforestation and reducing air pollution.",
      website: "https://swgreenmovement.org",
      location: "https://maps.google.com/?q=South+West+Green+Movement",
    },
    {
      name: "Clean Water Initiative",
      type: "Government Scheme",
      description:
        "Ensures clean drinking water supply to underprivileged areas.",
      website: "https://cleanwaterdelhi.gov.in",
      location: "https://maps.google.com/?q=Clean+Water+Initiative",
    },
    {
      name: "South West Plastic Ban Drive",
      type: "NGO",
      description:
        "Organizes awareness programs to eliminate single-use plastic.",
      website: "https://plasticbanswdelhi.org",
      location: "https://maps.google.com/?q=South+West+Plastic+Ban+Drive",
    },
    {
      name: "Delhi Urban Gardening Project",
      type: "Organization",
      description:
        "Encourages citizens to adopt urban farming and rooftop gardening.",
      website: "https://urbangardeningdelhi.org",
      location: "https://maps.google.com/?q=Delhi+Urban+Gardening+Project",
    },
    {
      name: "Eco Transport South West",
      type: "Government Scheme",
      description:
        "Provides incentives for electric bikes and public transport usage.",
      website: "https://ecotransportswdelhi.gov.in",
      location: "https://maps.google.com/?q=Eco+Transport+South+West",
    },
    {
      name: "South West Waste Management Initiative",
      type: "NGO",
      description:
        "Works on efficient waste segregation and recycling projects.",
      website: "https://wastemanagementswdelhi.org",
      location:
        "https://maps.google.com/?q=South+West+Waste+Management+Initiative",
    },
  ],
  "west-delhi": [
    {
      name: "West Delhi Environmental Protection Group",
      type: "NGO",
      description:
        "Focuses on tree plantation and reducing industrial pollution.",
      website: "https://wdepg.org",
      location:
        "https://maps.google.com/?q=West+Delhi+Environmental+Protection+Group",
    },
    {
      name: "Clean Yamuna Project",
      type: "Government Scheme",
      description: "Aims to clean and restore the Yamuna riverbanks.",
      website: "https://cleanyamunaproject.gov.in",
      location: "https://maps.google.com/?q=Clean+Yamuna+Project",
    },
    {
      name: "Zero Waste West Delhi",
      type: "NGO",
      description: "Encourages zero-waste lifestyle practices and composting.",
      website: "https://zerowastewestdelhi.org",
      location: "https://maps.google.com/?q=Zero+Waste+West+Delhi",
    },
    {
      name: "Delhi Green Energy Program",
      type: "Government Scheme",
      description: "Promotes the use of renewable energy and solar power.",
      website: "https://greenenergydelhi.gov.in",
      location: "https://maps.google.com/?q=Delhi+Green+Energy+Program",
    },
    {
      name: "Community Recycling Centers",
      type: "Organization",
      description: "Establishes local recycling centers for waste management.",
      website: "https://communityrecyclingwestdelhi.org",
      location: "https://maps.google.com/?q=Community+Recycling+Centers",
    },
    {
      name: "West Delhi Biodiversity Conservation",
      type: "NGO",
      description: "Works on restoring lost green spaces and biodiversity.",
      website: "https://biodiversitywestdelhi.org",
      location:
        "https://maps.google.com/?q=West+Delhi+Biodiversity+Conservation",
    },
  ],
};

export default districtData;
